/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ukk_wijoyo_2;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.MessageFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.JTable;
import javax.swing.*;
import java.awt.event.*;
import java.awt.*;
import java.awt.print.*;
import java.sql.Statement;
import java.text.*;
import javax.swing.table.DefaultTableModel;
import javax.print.PrintException;
import javax.swing.JFrame;
/**
 *
 * @author gaming
 */
public class rute extends javax.swing.JFrame {
        Connection conn         = null;
        ResultSet rs            = null;
        PreparedStatement pst   = null;
    /**
     * Creates new form rute
     */
    public rute() {
        initComponents();
        
            try {
                conn = koneksi.wijoyokonek();
                show_data();
                load_kereta();
                load_pesawat();
            } catch (SQLException ex) {
                Logger.getLogger(rute.class.getName()).log(Level.SEVERE, null, ex);
            }
    }
    
    private void show_data(){
        String perintah = "SELECT * FROM rute";
        try {
            pst = conn.prepareStatement(perintah);
            rs = pst.executeQuery();
            
            DefaultTableModel makan = new DefaultTableModel();
            makan.addColumn("ID");
            makan.addColumn("From");
            makan.addColumn("To");
            makan.addColumn("Harga");
            makan.addColumn("Nama Transport");
            makan.addColumn("depart date");
        
        while (rs.next()){
            makan.addRow(new Object[]{rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6)});
        }
        tblrute.setModel(makan);
        } catch (SQLException ex) {
            
        }
    }
    
    private void clear(){
        id.setText("");
        from.setText("");
        cbkereta.setSelectedItem("");
        cbpesawat.setSelectedItem("");
        to.setText("");
        harga.setText("");
        nama_trans.setText("");
        depart_date.setDate(null);
    }
    
    private void load_kereta(){
        try {
            Statement cs = conn.createStatement();
            ResultSet rs = cs.executeQuery("select * from kereta");
            while (rs.next()) {
                String item = rs.getString("id_kereta");
                cbkereta.addItem(item);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
        
    
}
    
    private void load_pesawat(){
        try {
            Statement cs = conn.createStatement();
            ResultSet rs = cs.executeQuery("select * from maskapai");
            while (rs.next()) {
                String item = rs.getString("id_maskapai");
                cbpesawat.addItem(item);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
        
    
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        harga = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        to = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cbkereta = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblrute = new javax.swing.JTable();
        from = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        add = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        update = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cbpesawat = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        nama_trans = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        depart_date = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("ID");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, -1, -1));
        jPanel1.add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 150, -1));
        jPanel1.add(harga, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 150, -1));

        jLabel3.setText("Harga");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, -1, -1));

        jLabel4.setText("Kereta");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 80, -1, -1));

        jLabel5.setText("From");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 80, -1, -1));
        jPanel1.add(to, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 110, 151, -1));

        jLabel6.setText("To");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 110, -1, -1));

        cbkereta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Pilih--" }));
        cbkereta.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbkeretaItemStateChanged(evt);
            }
        });
        jPanel1.add(cbkereta, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 80, 149, -1));

        tblrute.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblrute.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblruteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblrute);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 690, 230));
        jPanel1.add(from, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 80, 150, -1));

        jPanel2.setBackground(new java.awt.Color(221, 75, 57));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Aplikasi Ticketing");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Rute");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("X");
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 0, -1, -1));

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("-");
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 0, -1, -1));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("?");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 0, -1, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ukk_wijoyo_2/img/icons8_Tracks_24px.png"))); // NOI18N
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, -1, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-5, 0, 840, 70));

        jPanel3.setBackground(new java.awt.Color(34, 45, 50));

        jPanel4.setBackground(new java.awt.Color(44, 59, 65));

        add.setFont(new java.awt.Font("Segoe UI Black", 0, 11)); // NOI18N
        add.setForeground(new java.awt.Color(255, 255, 255));
        add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ukk_wijoyo_2/img/icons8_Add_New_24px.png"))); // NOI18N
        add.setText("Submit");
        add.setContentAreaFilled(false);
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });

        delete.setFont(new java.awt.Font("Segoe UI Black", 0, 11)); // NOI18N
        delete.setForeground(new java.awt.Color(255, 255, 255));
        delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ukk_wijoyo_2/img/icons8_Trash_Can_24px_1.png"))); // NOI18N
        delete.setText("Delete");
        delete.setContentAreaFilled(false);
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        clear.setFont(new java.awt.Font("Segoe UI Black", 0, 11)); // NOI18N
        clear.setForeground(new java.awt.Color(255, 255, 255));
        clear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ukk_wijoyo_2/img/icons8_Clear_Symbol_24px.png"))); // NOI18N
        clear.setText("Clear");
        clear.setContentAreaFilled(false);
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });

        update.setFont(new java.awt.Font("Segoe UI Black", 0, 11)); // NOI18N
        update.setForeground(new java.awt.Color(255, 255, 255));
        update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ukk_wijoyo_2/img/icons8_Pencil_24px.png"))); // NOI18N
        update.setText("Update");
        update.setContentAreaFilled(false);
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(add, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(delete)
                            .addComponent(clear)
                            .addComponent(update))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(add)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(delete)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(clear)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(update)
                .addGap(97, 97, 97))
        );

        jLabel9.setBackground(new java.awt.Color(34, 45, 50));
        jLabel9.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 204, 204));
        jLabel9.setText("Proses");

        jLabel10.setText("Wijoyo Wisnu M");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jLabel10)
                .addGap(24, 24, 24))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 110, 360));

        cbpesawat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Pilih--" }));
        cbpesawat.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbpesawatItemStateChanged(evt);
            }
        });
        jPanel1.add(cbpesawat, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 110, 149, -1));

        jLabel14.setText("Pesawat");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 110, -1, -1));

        nama_trans.setEnabled(false);
        jPanel1.add(nama_trans, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 140, 151, -1));

        jLabel15.setText("Nama Trans.");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 140, -1, -1));

        jLabel16.setText("Date");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 140, -1, -1));

        depart_date.setDateFormatString("yyyy-MM-dd");
        jPanel1.add(depart_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 140, 150, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 824, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblruteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblruteMouseClicked
        // TODO add your handling code here:
        int row = tblrute.getSelectedRow();
        String diklik = (tblrute.getModel().getValueAt(row, 0).toString());
        String sql = "SELECT * FROM rute WHERE id_rute='"+diklik+"'";

        try {
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();

            if((rs.next())){
                String tambah1 = rs.getString("id_rute");
                id.setText(tambah1);
                String tambah2 = rs.getString("depart_from");
                from.setText(tambah2);
                String tambah3 = rs.getString("depart_to");
                to.setText(tambah3);
                String tambah4 = rs.getString("harga");
                harga.setText(tambah4);
                String tambah5 = rs.getString("nama_transport");
                nama_trans.setText(tambah5);
                String tambah11 = rs.getString("depart_date");
                ((JTextField)depart_date.getDateEditor().getUiComponent()).setText(tambah11);
            }
        } catch (SQLException ex) {
            Logger.getLogger(maskapai.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tblruteMouseClicked

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        this.dispose();         // TODO add your handling code here:
    }//GEN-LAST:event_jLabel11MouseClicked

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        this.setState(ICONIFIED);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel12MouseClicked

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed

        try {
            String check = "SELECT * FROM rute WHERE id_rute='"+id.getText()+"'";
            pst = conn.prepareStatement(check);
            rs = pst.executeQuery();
            if((!rs.next())){

                if (!id.getText().isEmpty() && !harga.getText().isEmpty() && !to.getText().isEmpty()){
                    String query = "INSERT INTO rute (id_rute,depart_from,depart_to,harga,nama_transport,depart_date) value(?,?,?,?,?,?)";
                    pst = conn.prepareStatement(query);

                    pst.setString(1, id.getText());
                    pst.setString(2, from.getText());
                    pst.setString(3, to.getText());
                    pst.setString(4, harga.getText());
                    pst.setString(5, nama_trans.getText());
                    pst.setString(6, ((JTextField)depart_date.getDateEditor().getUiComponent()).getText());
                    
                    pst.execute();
                    JOptionPane.showMessageDialog(null, "Data Berhasil  Ditambah");
                    show_data();
                    clear();
                }

            }else{
                JOptionPane.showMessageDialog(null, "Data Sudah ada");
                clear();
            }

        } catch (SQLException ex) {
            Logger.getLogger(maskapai.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_addActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
        try {
            String sql = "DELETE FROM rute where id_rute = ?";
            pst = conn.prepareStatement(sql);
            pst.setString(1, id.getText());
            pst.execute();
            JOptionPane.showMessageDialog(null, "Data Successfuly Deleted");
            show_data();
            clear();
        } catch (SQLException ex) {
            Logger.getLogger(maskapai.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_deleteActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        clear();
    }//GEN-LAST:event_clearActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        // TODO add your handling code here:
        try {
            String sql = "UPDATE rute SET depart_from=?, depart_to=?, harga=?, nama_transport=?, depart_date=? where id_rute='"+id.getText()+"'";
            pst = conn.prepareStatement(sql);

                    
                    pst.setString(1, from.getText());
                    pst.setString(2, to.getText());
                    pst.setString(3, harga.getText());
                    pst.setString(4, nama_trans.getText());
                    pst.setString(5, ((JTextField)depart_date.getDateEditor().getUiComponent()).getText());

            pst.execute();

            JOptionPane.showMessageDialog(null, "Data Successfuly Updated");
            show_data();
        } catch (SQLException ex) {
            Logger.getLogger(maskapai.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_updateActionPerformed

    private void cbkeretaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbkeretaItemStateChanged
        // TODO add your handling code here:
        String perintah = "SELECT * FROM kereta WHERE id_kereta='"+cbkereta.getSelectedItem()+"'";
            try {
                pst = conn.prepareStatement(perintah);
                rs = pst.executeQuery();
                if((rs.next())){
                String tambaha = rs.getString("nama_kereta");
                nama_trans.setText(tambaha);
                cbpesawat.setSelectedItem(null);
            }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, ex);
            }
    }//GEN-LAST:event_cbkeretaItemStateChanged

    private void cbpesawatItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbpesawatItemStateChanged
        // TODO add your handling code here:
        String perintah = "SELECT * FROM maskapai WHERE id_maskapai='"+cbpesawat.getSelectedItem()+"'";
            try {
                pst = conn.prepareStatement(perintah);
                rs = pst.executeQuery();
                if((rs.next())){
                String tambaha = rs.getString("nama_maskapai");
                nama_trans.setText(tambaha);
                cbkereta.setSelectedItem(null);
            }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, ex);
            }
    }//GEN-LAST:event_cbpesawatItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(rute.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(rute.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(rute.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(rute.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new rute().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JComboBox<String> cbkereta;
    private javax.swing.JComboBox<String> cbpesawat;
    private javax.swing.JButton clear;
    private javax.swing.JButton delete;
    private com.toedter.calendar.JDateChooser depart_date;
    private javax.swing.JTextField from;
    private javax.swing.JTextField harga;
    private javax.swing.JTextField id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nama_trans;
    private javax.swing.JTable tblrute;
    private javax.swing.JTextField to;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
